### PR TITLE
Landing page resource tiles

### PR DESCRIPTION
**Pull request by lhelms2**
Change list of 'computing' and 'storage' docs links into tiles. The tiles dynamically change from 3-across to 2-across to 1-across based on screen size. Intend to keep the common system documentation links as they are (in a list).

RTD build: https://docs.ncsa.illinois.edu/en/tiles-final/

@craigsteffen , requesting your review for this PR into proposed_changes since it's a rather large change to have mixed into proposed_changes waiting for review. Once this PR is approved/merged, then I'll merge proposed_changes into main.

### CODE REVIEW

**Comment by lhelms2** [comment]
@craigsteffen I think I solved the left nav issue I was having, I moved the resource lists to the bottom. They'll get lower over time as new pages are added, but the one-look lists will always be a quick mouse scroll away. Please take a look and let me know what you think. 

https://docs.ncsa.illinois.edu/en/tiles-final/

(I still need to ask around about some of the tile images so that's why I've got the PR in draft.)

**Comment by craigsteffen** [comment]
Yep.  Resource list on the bottom is great.  That looks fine to me.

**Comment by lhelms2** [comment]
Need to verify the system applicability of the new 'group management' page, which will determine where it should live in the documentation. Greg was identified as a good person to ask about this. I'll work with Greg and Craig to resolve.

This was discussed/identified during the user documentation meeting on 9/11.

**Comment by lhelms2** [comment]
@craigsteffen  Alright, I think this is ready for final review before deployment. 
Here's the RTD build: https://docs.ncsa.illinois.edu/en/tiles-final/
Thank you

**Comment by craigsteffen** [comment]
@lhelms2 Thanks for the ping; I'll look at it soon.

**Comment by craigsteffen** [comment]
I'm doing a final pass through this.  However, 
@greghbauer 
could you look at this page, and in particular, how it's split out at the top of the page:  https://docs.ncsa.illinois.edu/en/tiles-final/account-mgmt/group-mgmt.html

to make sure that's correct with the current state of things?

**Comment by craigsteffen** [comment]
@lhelms2 
I'm fine with this.  I looked at the file changes; it looks like it's mostly visual editing stuff, which would show up in the preview if it wasn't right.  That looks fine to me, and I'm sure you've checked it as well.  

Greg slacked me back and confirmed that the breakdown of what systems used what methods to manage user groups is correct.  

Ship it.

**Pull request merged**
